# Generated by Django 4.2.11 on 2024-04-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dog_shelters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="description",
            field=models.TextField(max_length=200),
        ),
    ]
